/*.$file${./SM/Includes::signal.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: lamp.qm
* File:  ${./SM/Includes::signal.h}
*
* This code has been generated by QM 5.1.4 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${./SM/Includes::signal.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"
#include "app.h"

#define OFF   0
#define ON    1

enum LampSignals{
    SOFT_CLICK_SIG = Q_USER_SIG,
    HARD_CLICK_SIG,
    MAX_SIG
};


/*.$declare${LampSM} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*.${LampSM::Lamp} .........................................................*/
typedef struct {
/* protected: */
    QHsm super;

/* public: */
    uint8_t state;
} Lamp;

/* public: */
void Lamp_pushSwitch(Lamp * const me);
void Lamp_ctor(Lamp * const me);
void Lamp_holdSwitch(Lamp * const me);

/* protected: */
QState Lamp_initial(Lamp * const me, void const * const par);
QState Lamp_LED_RED(Lamp * const me, QEvt const * const e);
QState Lamp_BLINK(Lamp * const me, QEvt const * const e);
QState Lamp_LED_GREEN(Lamp * const me, QEvt const * const e);
/*.$enddecl${LampSM} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
